apiVersion: v1
kind: ConfigMap
metadata:
  name: "temporalminikube-dynamic-config"
  labels:
    app.kubernetes.io/name: temporal
    helm.sh/chart: temporal-0.22.1
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: 1.20.3
    app.kubernetes.io/part-of: temporal
data:
  config_template.yaml: |-
    HistoryCacheMaxSize:
    - value: 8192
      constraints: {}
    EventsCacheMaxSize:
    - value: 8192
      constraints: {}
    history.cacheMaxSize:
    - value: 8192
      constraints: {}
    history.eventsCacheMaxSize:
    - value: 8192
      constraints: {}
 